package com.myplace.rest.constant;



public interface MyPlaceWebConstant {
	String STATUS = "status";
	String MESSAGE = "message";
	String CODE = "code";
	String STATUS_SUCCESS = "success";
	String STATUS_ERROR = "error";
	String STATUS_WARNING = "warning";
	String MEDIA_CREATE_ERROR = "Media creation is failed due to some reason.";
	String ADVT_CREATE_ERROR = "Advt creation is failed due to some reason.";
	String DATA_NOT_UPLOADED = "Data upload parameters are null.";
	String ERROR_MESSAGE = "Request is failed due to some reason.";
	String NO_RESULT_FOUND = "No result found.";
	String DEFAULT_VIEW_NAME = "json";
	String RESPONSE = "jsonData";
	String REQUEST_TYPE = "requesttype";
	Integer ERROR_CODE = 0;
	Integer SUCCESS_CODE = 1;
	Integer DEFAULT_ADVT_LIMIT = 10;
	String YES = "1";
	String CHALK_AUTHETICATION_PROPERTY = "authparams";
	String CHALK_AUTHETICATION_IMEI_PARAM = "imei";
	String CHALK_AUTHETICATION_USER_NAME_PARAM = "username";
	String CHALK_AUTHETICATION_AUTHKEY_PARAM = "authkey";
	String CHALK_AUTHETICATION_PASSWORD_PARAM = "password";
	String CHALK_AUTHETICATION_LOGIN_MODE_PARAM = "loginmode";
	String CHALK_AUTHETICATION_PARTNER_USER_KEY_PARAM = "partneruserkey";
	String CHALK_AUTHETICATION_APP_ID_PARAM = "appid";
	String CHALK_AUTHETICATION_AUTHKEY = "8be7a063a19fd760850351fcbc43eec9";
	String LOCATION="loc";
	String TAG="tag";
	String ADVT = "advt";
	String LONG = "long";
	String LAT = "lat";
	String ZOOM = "zoom";
	String ADVT_TEMPLATE = "advtTemplate";
	String USERID = "userId";
	String ADVTCODE = "advtCode";
	String TYPE = "type";
	String COUNTRY_CODE = "countryCode";
	String DEFAULT_COUNTRY_CODE = "IN";
	String CATEGORIES = "cats";
	String ABOUT_US = "abt";
	String FEEDBACK = "feedback";
	String SUB_CATEGORIES = "subCats";
	String CATEGORY_ID = "catId";
	String BUSINESS_ID = "businessId";
	String BUSINESS_LIST = "bussList";
	String BUSINESS_DETAIL = "bussDtl";
	String USER_DETAIL = "usrDtl";
	String SLIMIT="sLimit";
	String NOTIFICATION_LIST = "notifList";
	String EMAIL_VERIFICATION_FAILURE_VIEW_NAME = "emailVerificationFailure";
	String EMAIL_VERIFICATION_SUCCESS_VIEW_NAME = "emailVerificationSuccess";
	String PASSWORD_CHANGE_FAILURE_VIEW_NAME = "passwordChangeFailure";
	String PASSWORD_CHANGE_SUCCESS_VIEW_NAME = "passwordChangeSuccess";
	String REASONLIST = "reasonList";
	String BUSINESS_REPORT_LIST = "bReportList";
}
